Repository pento/free-as-in-speech, pull requests merged in 2021-03, with the labels that each got.

#23 Rewrite the WXR package to store data in IndexedDB
  .eslintrc-md.js
  .eslintrc.js
  .npmpackagejsonlintrc.json
  distribution/action.html
  distribution/manifest.json
  jest.config.js
  package-lock.json
  package.json
  packages/wxr/README.md
  packages/wxr/package.json
  packages/wxr/src/1.2/index.js
  packages/wxr/src/1.2/schema.js
  packages/wxr/src/1.2/test/__snapshots__/authors.js.snap
  packages/wxr/src/1.2/test/__snapshots__/basic.js.snap
  packages/wxr/src/1.2/test/__snapshots__/comments.js.snap
  packages/wxr/src/1.2/test/__snapshots__/posts.js.snap
  packages/wxr/src/1.2/test/__snapshots__/sitemeta.js.snap
  packages/wxr/src/1.2/test/__snapshots__/terms.js.snap
  packages/wxr/src/1.2/test/authors.js
  packages/wxr/src/1.2/test/basic.js
  packages/wxr/src/1.2/test/comments.js
  packages/wxr/src/1.2/test/posts.js
  packages/wxr/src/1.2/test/sitemeta.js
  packages/wxr/src/1.2/test/terms.js
  packages/wxr/src/index.js
  packages/wxr/src/test/index.js
  source/background.js
  source/content.js
  source/services/wix/extractors/communities-blog-app/index.js
  source/services/wix/extractors/site-meta-app/index.js
  source/services/wix/index.js
  test/integration/wix/__snapshots__/fetch-from-wix-har.test.js.snap
  test/integration/wix/fetch-from-wix-har.test.js
  test/integration/wix/fixtures/easyblog.wxr
  test/integration/wix/fixtures/wix-basic.wxr
  test/setup-env.js
  webpack.config.js
Labels: [Package] WXR, [Status] In Progress, [Type] Enhancement

#32 Dependency upgrades.
  bin/export-from-har.js
  package-lock.json
  package.json
  packages/wxr/src/1.2/index.js
Labels: [Type] Build Tooling

#31 Extension UI: Show the progress during export
  bin/lib/get-wxr-from-wix-har.js
  distribution/action.css
  distribution/action.html
  source/background.js
  source/popup.js
  source/services/index.js
  source/services/wix/extractors/communities-blog-app/index.js
  source/services/wix/extractors/easy-blog-app/index.js
  source/services/wix/extractors/media-manager/index.js
  source/services/wix/extractors/site-meta-app/index.js
  source/services/wix/index.js
Labels: [Type] Enhancement

#30 Add tool to anonymize HAR files
  docs/contributors/command-line.md
  package-lock.json
  packages/fetch-from-har/bin/anonymize-har.js
  packages/fetch-from-har/package.json
Labels: [Package] Fetch From HAR

#34 Upgrade to npm 7.
  .npmrc
  package-lock.json
  package.json
Labels: [Type] Build Tooling

#33 Switch the Popup UI to using React
  .babelrc
  .eslintrc.js
  .github/workflows/strings.yml
  bin/build-language-pack.js
  distribution/action.css
  distribution/action.html
  languages/free-as-in-speech.pot
  package-lock.json
  package.json
  source/action.js
  source/background.js
  source/popup.js
  source/services/index.js
  source/services/wix/index.js
  test/integration/wix/fetch-from-wix-har.test.js
  webpack.config.js
Labels: [Status] In Progress, [Type] Enhancement

#35 Upgrade dependencies
  package-lock.json
  package.json
Labels: [Type] Build Tooling

#36 Add a linting pre-commit hook.
  .github/workflows/test.yml
  .husky/.gitignore
  .husky/pre-commit
  .lintstagedrc.json
  package-lock.json
  package.json
Labels: [Type] Build Tooling, [Type] Code Quality

#37 Add paging support to the Community Blog extractor
  source/services/wix/extractors/communities-blog-app/index.js
  source/services/wix/extractors/communities-blog-app/test/index.js
  test/integration/wix/fixtures/wix-basic.har
Labels: [CMS] Wix, [Type] Enhancement

#41 Update the out of date dependencies.
  package-lock.json
  package.json
Labels: [Type] Build Tooling

#42 Wix: Add support for full-width blocks in the community blog app.
  source/services/wix/extractors/communities-blog-app/block-mapping.js
  source/services/wix/extractors/communities-blog-app/test/__snapshots__/block-mapping.js.snap
  source/services/wix/extractors/communities-blog-app/test/block-mapping.js
Labels: [Type] Bug
